# Generated by Django 5.2.13 on 2026-04-13 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fraudcase',
            name='category',
        ),
        migrations.RemoveField(
            model_name='fraudcase',
            name='target_info',
        ),
        migrations.AddField(
            model_name='fraudcase',
            name='fraud_info',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fraudcase',
            name='fraud_type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fraudcase',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='승인 여부'),
        ),
        migrations.AlterField(
            model_name='fraudcase',
            name='description',
            field=models.TextField(),
        ),
    ]
