# Generated by Django 5.2.13 on 2026-04-13 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FraudCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='사기 유형')),
                ('target_info', models.CharField(max_length=100, verbose_name='사기 의심 정보(계좌/번호)')),
                ('description', models.TextField(verbose_name='피해 상세 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
